const TicketActionTypes = {
    FETCH_TICKETS_START: 'FETCH_TICKETS_START',
    FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
    FETCH_TICKETS_FAILURE: 'FETCH_TICKETS_FAILURE'
}

export default TicketActionTypes;