const ProjectsActionTypes = {
    FETCH_PROJECTS_START: 'FETCH_PROJECTS_START',
    FETCH_PROJECTS_SUCCESS: 'FETCH_PROJECTS_SUCCESS',
    FETCH_PROJECTS_FAILURE: 'FETCH_PROJECTS_FAILURE',

    CREATE_PROJECT_START: 'CREATE_PROJECT_START',
    CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
    CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',

    FETCH_USERS_PROJECTS_START: 'FETCH_USERS_PROJECTS_START',
    FETCH_USERS_PROJECTS_SUCCESS: 'FETCH_USERS_PROJECTS_SUCCESS',
    FETCH_USERS_PROJECTS_FAILURE: 'FETCH_USERS_PROJECTS_FAILURE',

    UPDATE_USERS_PROJECTS_START: 'UPDATE_USERS_PROJECTS',
    UPDATE_USERS_PROJECTS_SUCCESS: 'UPDATE_USERS_PROJECTS_SUCCESS',
    UPDATE_USERS_PROJECTS_FAILURE: 'UPDATE_USERS_PROJECTS_FAILURE',
    
    SELECT_PROJECT: 'SELECT_PROJECT',
    UPDATE_PROJECT_SEARCH_KEY: 'UPDATE_PROJECT_SEARCH_KEY',
}

export default ProjectsActionTypes;