const UserDBActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE',
    UPDATE_SEARCH_KEY: 'UPDATE_SEARCH_KEY',
    UPDATE_USER_ROLE: 'UPDATE_USER_ROLE',
}

export default UserDBActionTypes;